/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_skype_connector_linux_SkypeFramework */

#ifndef _Included_com_skype_connector_linux_SkypeFramework
#define _Included_com_skype_connector_linux_SkypeFramework
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_skype_connector_linux_SkypeFramework
 * Method:    setup0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_skype_connector_linux_SkypeFramework_setup0
  (JNIEnv *, jclass);

/*
 * Class:     com_skype_connector_linux_SkypeFramework
 * Method:    runEventLoop0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_skype_connector_linux_SkypeFramework_runEventLoop0
  (JNIEnv *, jclass);

/*
 * Class:     com_skype_connector_linux_SkypeFramework
 * Method:    isRunning0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_skype_connector_linux_SkypeFramework_isRunning0
  (JNIEnv *, jclass);

/*
 * Class:     com_skype_connector_linux_SkypeFramework
 * Method:    sendCommand0
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_skype_connector_linux_SkypeFramework_sendCommand0
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_skype_connector_linux_SkypeFramework
 * Method:    stopEventLoop0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_skype_connector_linux_SkypeFramework_stopEventLoop0
  (JNIEnv *, jclass);

/*
 * Class:     com_skype_connector_linux_SkypeFramework
 * Method:    closeDisplay0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_skype_connector_linux_SkypeFramework_closeDisplay0
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
